# Generated by Django 6.1 on 2026-08-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='domaine',
            field=models.CharField(choices=[('geologie', 'Géologie & Sondage'), ('securite', 'Sécurité Minière & HSE'), ('exploitation', 'Exploitation & Cartographie'), ('traitement', 'Traitement du Minerai'), ('topographie', 'Topographie & SIG'), ('general', 'Général')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='formation',
            name='duree_totale_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Durée totale calculée automatiquement'),
        ),
        migrations.CreateModel(
            name='RessourceComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_ressource', models.CharField(choices=[('fichier', 'Fichier'), ('lien', 'Lien web')], default='fichier', max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='formations/ressources/')),
                ('lien_web', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='courses.formation')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='formations/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Ou lien vidéo externe (YouTube, etc.)', null=True)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.formation')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
