# Generated by Django 6.1 on 2026-08-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_inscription_progressionlecon'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecon',
            name='duree_secondes',
            field=models.PositiveIntegerField(default=0, help_text='Durée en secondes (calculée automatiquement)'),
        ),
        migrations.AlterField(
            model_name='videolecon',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Durée en minutes (calculée automatiquement)'),
        ),
    ]
