# Generated by Django 6.1 on 2026-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_videolecon_duree_secondes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeexamen',
            name='numero_certificat',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
