# Generated by Django 6.1 on 2026-08-21 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tentativeexamen_numero_certificat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('inactif', 'Inactif')], default='inactif', max_length=10)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('reseau', models.CharField(choices=[('airtel', 'Airtel Money'), ('orange', 'Orange Money'), ('mpesa', 'M-Pesa')], default='airtel', max_length=20)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_externe', models.CharField(help_text='ID transaction MaishaPay', max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='CDF', max_length=10)),
                ('telephone', models.CharField(help_text='Numéro Mobile Money du payeur', max_length=20)),
                ('reseau', models.CharField(default='airtel', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('metadata_reponse', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.abonnement')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
