# Generated by Django 6.1 on 2026-08-22 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_abonnement_transactionpaiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='reseau',
            field=models.CharField(choices=[('airtel', 'Airtel Money'), ('vodacom', 'Vodacom M-Pesa'), ('orange', 'Orange Money'), ('africell', 'Africell Money')], default='airtel', max_length=20),
        ),
        migrations.CreateModel(
            name='ProlongationAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_ajoutes', models.PositiveIntegerField(default=30)),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('ancienne_date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nouvelle_date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_prolongation', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prolongations', to='courses.abonnement')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prolongations_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Prolongation d'abonnement",
                'verbose_name_plural': "Prolongations d'abonnement",
                'ordering': ['-date_prolongation'],
            },
        ),
    ]
