# Generated by Django 6.1 on 2026-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_abonnement_reseau_prolongationabonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monnaie', models.CharField(choices=[('CDF', 'Franc congolais (CDF)'), ('USD', 'Dollar américain (USD)')], default='CDF', max_length=3)),
                ('montant_abonnement', models.DecimalField(decimal_places=2, default=10000, help_text="Montant de l'abonnement mensuel", max_digits=10)),
                ('duree_abonnement_jours', models.PositiveIntegerField(default=30)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
    ]
