# Generated by Django 6.1 on 2026-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_parametreplateforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='fichier_pdf',
        ),
        migrations.RemoveField(
            model_name='ressourcecomplementaire',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='videolecon',
            name='fichier_video',
        ),
        migrations.AddField(
            model_name='formation',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text="URL de l'image de couverture (Cloudinary, etc.)"),
        ),
        migrations.AddField(
            model_name='lecon',
            name='pdf_url',
            field=models.TextField(blank=True, default='', help_text='URL du PDF uploadé (Cloudinary, etc.)'),
        ),
        migrations.AddField(
            model_name='ressourcecomplementaire',
            name='fichier_url',
            field=models.TextField(blank=True, default='', help_text='URL du fichier uploadé (Cloudinary, etc.)'),
        ),
        migrations.AddField(
            model_name='videolecon',
            name='video_file_url',
            field=models.TextField(blank=True, default='', help_text='URL du fichier vidéo uploadé (Cloudinary, etc.)'),
        ),
    ]
