# Generated by Django 6.1 on 2026-08-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_replace_filefields_with_text_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la formation souhaitée', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Pourquoi cette formation ?')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('vue', 'Vue'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=15)),
                ('reponse_formateur', models.TextField(blank=True, help_text='Réponse du formateur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation', to=settings.AUTH_USER_MODEL)),
                ('formation_existante', models.ForeignKey(blank=True, help_text='Formation existante demandée (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='courses.formation')),
            ],
            options={
                'verbose_name': 'Demande de formation',
                'verbose_name_plural': 'Demandes de formation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
