# Generated by Django 6.1 on 2026-10-05 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_parametreplateforme_prix_certificat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametreplateforme',
            name='prix_certificat',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('document', 'Document'), ('autre', 'Autre')], default='photo', max_length=10)),
                ('path', models.TextField(db_index=True, help_text="Chemin relatif du fichier dans MEDIA_ROOT (ex: 'media/photo/2026/08/01/xxxx.jpg')")),
                ('titre', models.CharField(blank=True, default='', max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média téléversé',
                'verbose_name_plural': 'Médias téléversés',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.DeleteModel(
            name='CommandeCertificat',
        ),
    ]
